import 'package:mail_model/mail_model.dart';
import 'package:mail_sieve/mail_sieve.dart';
import 'package:test/test.dart';

const _account = MailAccount(
  id: 'acc',
  email: 'me@example.org',
  displayName: 'Mailcow',
  provider: ProviderKind.generic,
  authKind: AuthKind.password,
  incoming: ServerConfig(protocol: ServerProtocol.imap, host: 'mail.example.org', port: 993),
);

Mailbox _box(String account, String path, [MailboxRole role = MailboxRole.none]) =>
    Mailbox(id: MailIds.mailbox(account, path), accountId: account, name: path, path: path, role: role);

final _mailboxes = [
  _box('acc', 'INBOX', MailboxRole.inbox),
  _box('acc', 'Junk', MailboxRole.junk),
  _box('acc', 'Lists/Dev'),
  _box('other', 'Receipts'),
  _box('acc', 'Receipts'),
  _box('other', 'Only There'),
];

final _target = SieveTarget(account: _account, mailboxes: _mailboxes, now: DateTime(2026, 10, 4));

void main() {
  test('a server script with flags, filing, forwarding and stop', () {
    final rules = [
      Rule(
        id: 'r1',
        name: 'Dev list',
        condition: 'header:"List-Id=dev.example.org"',
        actions: [MoveToMailboxAction(MailIds.mailbox('acc', 'Lists/Dev')), const MarkReadAction()],
        location: RuleLocation.server,
        stopProcessing: true,
      ),
      const Rule(
        id: 'r2',
        name: 'Boss',
        condition: 'from:boss@example.org',
        actions: [FlagAction(), AddTagAction(r'$label1'), ForwardAction('me@phone.example')],
        location: RuleLocation.server,
        order: 1,
      ),
      const Rule(id: 'r3', name: 'Device only', condition: 'f:x', actions: [FlagAction()]),
    ];
    final script = generateLoupeScript(rules, _target);
    expect(script.problems, isEmpty);
    expect(script.text, '''
# Loupe rules for me@example.org. Generated by Loupe, which replaces
# this script whenever the rules change: edit them in Loupe, not here.
# loupe-script: 1
require ["copy", "fileinto", "imap4flags", "mailbox"];

# Rule: Dev list
# loupe-rule: {"id":"r1","name":"Dev list","condition":"header:\\"List-Id=dev.example.org\\"","actions":[{"type":"move","mailboxId":"acc|Lists%2FDev"},{"type":"markRead"}],"enabled":true,"accountIds":[],"stop":true}
if header :contains "List-Id" "dev.example.org" {
  addflag "\\\\Seen";
  fileinto :create "Lists/Dev";
  stop;
}

# Rule: Boss
# loupe-rule: {"id":"r2","name":"Boss","condition":"from:boss@example.org","actions":[{"type":"flag"},{"type":"addTag","keyword":"\$label1"},{"type":"forward","address":"me@phone.example","keepCopy":true}],"enabled":true,"accountIds":[],"stop":false}
if address :all :is "from" "boss@example.org" {
  addflag "\\\\Flagged";
  addflag "\$label1";
  redirect :copy "me@phone.example";
}
''');
    expect(checkSieveScript(script.text, loupeSieveExtensions), isEmpty);
  });

  test('scripts round-trip: Loupe reads its own rules back', () {
    final rules = [
      Rule(
        id: 'a',
        name: 'Receipts “2026”\nsecond line',
        condition: 'from:@shop.example s:receipt',
        actions: [MoveToMailboxAction(MailIds.mailbox('other', 'Receipts'))],
        location: RuleLocation.server,
        accountIds: const {'acc', 'other'},
      ),
      const Rule(
        id: 'b',
        name: 'Off',
        condition: 'f:x',
        actions: [FlagAction()],
        location: RuleLocation.server,
        enabled: false,
        order: 1,
      ),
      const Rule(
        id: 'c',
        name: 'Unread',
        condition: 'is:unread',
        actions: [FlagAction()],
        location: RuleLocation.server,
        order: 2,
      ),
    ];
    final script = generateLoupeScript(rules, _target);
    expect(isLoupeScript(script.text), isTrue);
    expect(parseLoupeScript(script.text), rules);
    // The folder of another account is the one with the same path here.
    expect(script.text, contains('fileinto :create "Receipts";'));
    expect(script.text, contains('# Rule: Off (off)'));
    expect(script.text, contains('# Rule: Receipts “2026” second line\n'));
    expect(script.problems.keys, ['c']);
    expect(script.text, contains('# Rule: Unread (not on this server: “Unread”: new mail has no read'));
    expect(parseLoupeScript('require "fileinto";\nif true { keep; }'), isEmpty);
  });

  test('rules report actions the server lacks and folders it lacks', () {
    final bare = SieveTarget(account: _account, mailboxes: _mailboxes, extensions: const {}, now: DateTime(2026));
    final rule = Rule(
      id: 'x',
      name: 'x',
      condition: 's:x',
      actions: [MoveToMailboxAction(MailIds.mailbox('other', 'Only There')), const AddTagAction('work')],
      location: RuleLocation.server,
    );
    final c = compileRule(rule, bare);
    expect(c.code, isEmpty);
    expect(c.problems, [
      'Mailcow has no folder “Only There”',
      'the server can’t set flags or tags (no imap4flags extension)',
    ]);
    expect(compileRule(rule, _target).problems, isEmpty);
    expect(
      compileRule(const Rule(id: 'f', name: 'f', condition: '', actions: [ForwardAction('nope')]), _target).problems,
      ['“nope” isn’t an email address to forward to'],
    );
  });

  test('account terms resolve per account; junk files into Junk; keep stops', () {
    const rule = Rule(
      id: 'j',
      name: 'Spam',
      condition: 'acc:mailcow s:winner',
      actions: [MarkJunkAction(), MoveToMailboxAction('acc|Receipts')],
      location: RuleLocation.server,
    );
    expect(compileRule(rule, _target).code, '''
if header :contains "subject" "winner" {
  addflag "\$Junk";
  fileinto "Junk";
}''');
    final elsewhere = compileRule(rule.copyWith(condition: 'acc:gmail s:winner'), _target);
    expect(elsewhere.code, isEmpty);
    expect(elsewhere.problems, isEmpty);
    final keep = compileRule(const Rule(id: 'k', name: 'k', condition: '', actions: [KeepInInboxAction()]), _target);
    expect(keep.code, 'keep;\nstop;');
    expect(
      compileRule(
        const Rule(id: 'n', name: 'n', condition: 'f:x', actions: [ForwardAction('a@b.example', keepCopy: false)]),
        SieveTarget(account: _account, extensions: const {'fileinto'}),
      ).code,
      'if header :contains "from" "x" {\n  redirect "a@b.example";\n}',
    );
    expect(
      compileRule(
        const Rule(id: 'n', name: 'n', condition: 'f:x', actions: [ForwardAction('a@b.example')]),
        SieveTarget(account: _account, extensions: const {}),
      ).code,
      'if header :contains "from" "x" {\n  redirect "a@b.example";\n  keep;\n}',
    );
  });

  group('include into the active script', () {
    test('adds a require after the leading ones and the include at the end', () {
      const sogo = '''
# Sieve filter
require ["vacation", "fileinto"];
require "envelope"; # for vacation
if header :contains "subject" "x" {
  fileinto "X";
}
''';
      final edit = planInclude(sogo)!;
      expect(edit.after, '''
# Sieve filter
require ["vacation", "fileinto"];
require "envelope"; # for vacation
require "include";
if header :contains "subject" "x" {
  fileinto "X";
}

$includeComment
include :personal "loupe";
''');
      expect(edit.addedLines, ['require "include";', includeComment, 'include :personal "loupe";']);
      expect(includesScript(edit.after), isTrue);
      expect(planInclude(edit.after), isNull);
      expect(checkSieveScript(edit.after, {'vacation', 'fileinto', 'envelope', 'include'}), isEmpty);
    });

    test('keeps an existing include require; works without requires or newline', () {
      expect(
        planInclude('require ["include"];\nkeep;')!.after,
        'require ["include"];\nkeep;\n\n$includeComment\ninclude :personal "loupe";\n',
      );
      expect(
        planInclude('# hi\nkeep;')!.after,
        '# hi\nrequire "include";\nkeep;\n\n$includeComment\ninclude :personal "loupe";\n',
      );
      expect(planInclude('require "fileinto";')!.after, startsWith('require "fileinto";\nrequire "include";\n'));
      expect(planInclude('')!.after, 'require "include";\n\n$includeComment\ninclude :personal "loupe";\n');
    });

    test('recognises includes, not commented ones or other scripts', () {
      expect(includesScript('require "include";\ninclude "loupe";'), isTrue);
      expect(includesScript('require "include"; include :once :personal "loupe" ;'), isTrue);
      expect(includesScript('# include :personal "loupe";\nkeep;'), isFalse);
      expect(includesScript('/* include "loupe"; */ keep;'), isFalse);
      expect(includesScript('include :personal "loupe2";'), isFalse);
      expect(includesScript('if header :is "x" "include \\"loupe\\";" { keep; }'), isFalse);
    });
  });

  test('the checker finds what CHECKSCRIPT would', () {
    expect(checkSieveScript('require "body";', {'fileinto'}), [
      "line 1: require command: unknown Sieve capability 'body'",
    ]);
    expect(checkSieveScript('\nfileinto "x";', {'fileinto'}), [
      "line 2: unknown command 'fileinto' (maybe you need to require the capability 'fileinto')",
    ]);
    expect(checkSieveScript('if true { keep;', const {}), ["line 1: '{' is never closed"]);
    expect(checkSieveScript('keep; "open', const {}), ['line 1: unterminated string']);
  });
}
