// Regenerates lib/src/windows_zones.dart from CLDR's windowsZones.xml:
//
//   curl -LO https://raw.githubusercontent.com/unicode-org/cldr/main/common/supplemental/windowsZones.xml
//   dart run tool/update_windows_zones.dart windowsZones.xml
//
// Outlook and Exchange write Windows zone names as TZIDs ("Pacific Standard
// Time"), and older versions the display names ("(UTC-08:00) Pacific Time (US
// & Canada)"); the table maps both to IANA names (the "001" territory, CLDR's
// default for each Windows zone).
import 'dart:io';

void main(List<String> args) {
  final source = File(args.isEmpty ? 'windowsZones.xml' : args.first).readAsStringSync();
  final names = <String, String>{};
  final display = <String, String>{};
  String? comment;
  for (final line in source.split('\n')) {
    final c = RegExp(r'<!--\s*(\(UTC.*?)\s*-->').firstMatch(line);
    if (c != null) {
      comment = c[1]!.replaceAll('&amp;', '&').trim();
      continue;
    }
    final m = RegExp(r'<mapZone other="([^"]+)" territory="001" type="([^"]+)"/>').firstMatch(line);
    if (m == null) continue;
    final windows = m[1]!.replaceAll('&amp;', '&');
    final iana = m[2]!.split(' ').first;
    names[windows] = iana;
    if (comment != null) display[comment] = iana;
    comment = null;
  }
  final version = RegExp(r'typeVersion="([^"]+)"').firstMatch(source)?[1] ?? '?';
  String quote(String s) => "'${s.replaceAll(r'\', r'\\').replaceAll("'", r"\'")}'";
  final out = StringBuffer()
    ..writeln('// Generated by tool/update_windows_zones.dart from CLDR windowsZones.xml (tz $version); do not edit.')
    ..writeln('//')
    ..writeln('// Copyright © 1991-2026 Unicode, Inc. CLDR data, under the Unicode License V3')
    ..writeln('// (SPDX-License-Identifier: Unicode-3.0): permission is granted, free of charge, to deal in the')
    ..writeln('// data files without restriction, provided that this copyright and permission notice appear with')
    ..writeln('// all copies. THE DATA FILES ARE PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND.')
    ..writeln('// See https://www.unicode.org/license.txt.')
    ..writeln()
    ..writeln('/// Windows time zone names, as Outlook writes them in TZID, to IANA names.')
    ..writeln('library;')
    ..writeln()
    ..writeln('const windowsZoneNames = <String, String>{');
  for (final MapEntry(:key, :value) in names.entries) {
    out.writeln('  ${quote(key)}: ${quote(value)},');
  }
  out
    ..writeln('};')
    ..writeln()
    ..writeln('/// Windows display names ("(UTC+01:00) Amsterdam, Berlin, …"), which older Outlook versions')
    ..writeln('/// write in TZID, to IANA names.')
    ..writeln('const windowsZoneDisplayNames = <String, String>{');
  for (final MapEntry(:key, :value) in display.entries) {
    out.writeln('  ${quote(key)}: ${quote(value)},');
  }
  out.writeln('};');
  File('lib/src/windows_zones.dart').writeAsStringSync(out.toString());
  stdout.writeln('${names.length} names, ${display.length} display names');
}
