targets:
  $default:
    builders:
      drift_dev:
        generate_for:
          - lib/src/schema.dart
        options:
          sql:
            dialect: sqlite
            options:
              version: "3.45"
              modules: [json1, fts5]
