import 'dart:convert';
import 'dart:typed_data';

import 'package:mail_model/mail_model.dart';

/// A minimal, valid one-page PDF showing [title], so attachment viewers have
/// something real to open.
Uint8List tinyPdf(String title) {
  final safe = title.replaceAll(RegExp(r'[()\\]'), '').replaceAll(RegExp(r'[^\x20-\x7E]'), '-');
  final content =
      'BT /F1 22 Tf 72 720 Td ($safe) Tj ET\n'
      'BT /F1 12 Tf 72 690 Td (Demo document generated by Loupe.) Tj ET';
  final objects = [
    '<< /Type /Catalog /Pages 2 0 R >>',
    '<< /Type /Pages /Kids [3 0 R] /Count 1 >>',
    '<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Contents 4 0 R '
        '/Resources << /Font << /F1 5 0 R >> >> >>',
    '<< /Length ${content.length} >>\nstream\n$content\nendstream',
    '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>',
  ];
  final out = StringBuffer('%PDF-1.4\n');
  final offsets = <int>[];
  for (final (i, body) in objects.indexed) {
    offsets.add(out.length);
    out.write('${i + 1} 0 obj\n$body\nendobj\n');
  }
  final xref = out.length;
  out.write('xref\n0 ${objects.length + 1}\n0000000000 65535 f \n');
  for (final o in offsets) {
    out.write('${o.toString().padLeft(10, '0')} 00000 n \n');
  }
  out.write('trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n$xref\n%%EOF\n');
  return Uint8List.fromList(latin1.encode(out.toString()));
}

/// An iCalendar invitation for a one-hour event starting at [start].
Uint8List calendarFile(String summary, DateTime start) {
  String stamp(DateTime d) {
    final u = d.toUtc();
    String two(int v) => v.toString().padLeft(2, '0');
    return '${u.year}${two(u.month)}${two(u.day)}T${two(u.hour)}${two(u.minute)}00Z';
  }

  return Uint8List.fromList(
    utf8.encode(
      'BEGIN:VCALENDAR\r\nVERSION:2.0\r\nPRODID:-//Loupe//Demo//EN\r\nMETHOD:REQUEST\r\nBEGIN:VEVENT\r\n'
      'UID:${start.millisecondsSinceEpoch}@northwind.example\r\nDTSTART:${stamp(start)}\r\n'
      'DTEND:${stamp(start.add(const Duration(hours: 1)))}\r\nSUMMARY:$summary\r\n'
      'ORGANIZER;CN=Dana Okafor:mailto:dana.okafor@northwind.example\r\nLOCATION:Lighthouse (3rd floor)\r\n'
      'END:VEVENT\r\nEND:VCALENDAR\r\n',
    ),
  );
}

/// RFC 5322 date, e.g. `Sat, 04 Oct 2026 14:05:09 +0000`.
String rfc5322Date(DateTime date) {
  const days = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'];
  const months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
  final u = date.toUtc();
  String two(int v) => v.toString().padLeft(2, '0');
  return '${days[u.weekday - 1]}, ${two(u.day)} ${months[u.month - 1]} ${u.year} '
      '${two(u.hour)}:${two(u.minute)}:${two(u.second)} +0000';
}

/// RFC 2047 encoding for header values that aren't plain ASCII.
String encodeHeaderValue(String value) {
  if (!value.runes.any((r) => r > 126)) return value;
  return '=?UTF-8?B?${base64.encode(utf8.encode(value))}?=';
}

String formatAddressHeader(List<EmailAddress> addresses) => addresses
    .map((a) => a.name == null || a.name!.isEmpty ? a.email : '${encodeHeaderValue(a.name!)} <${a.email}>')
    .join(', ');

/// Base64 wrapped at 76 characters, as MIME wants it.
String wrappedBase64(List<int> bytes) {
  final b = base64.encode(bytes);
  final out = StringBuffer();
  for (var i = 0; i < b.length; i += 76) {
    out.write(b.substring(i, i + 76 > b.length ? b.length : i + 76));
    out.write('\r\n');
  }
  return out.toString();
}
