import 'dart:math';
import 'dart:typed_data';

import 'package:mail_model/mail_model.dart';

import 'demo_bodies.dart';
import 'demo_mime.dart';

/// An attachment of a demo message and where its bytes come from.
final class DemoAttachment {
  const DemoAttachment(this.attachment, {this.asset, this.generate});

  final Attachment attachment;

  /// Asset path of the bytes (images).
  final String? asset;

  /// Generated bytes (PDFs, calendar files, documents).
  final Uint8List Function()? generate;
}

/// One message of the demo mailbox: its summary plus everything needed to
/// produce its content and raw source.
final class DemoMessage {
  DemoMessage({
    required this.summary,
    this.html,
    this.text,
    this.isFlowed = false,
    this.attachments = const [],
    this.extraHeaders = const [],
    this.authenticationFails = false,
  });

  EmailSummary summary;
  final String? html;
  final String? text;
  final bool isFlowed;
  final List<DemoAttachment> attachments;

  /// Headers beyond the standard ones (List-Id, X-Mailer…).
  final List<(String, String)> extraHeaders;

  /// Fails DKIM/SPF/DMARC in Authentication-Results (the phishing message).
  final bool authenticationFails;

  String get id => summary.id;
}

/// The fictional owner of the demo mailbox and the people they write with.
abstract final class DemoPeople {
  static const personal = EmailAddress('sam.rivera@gmail.example', 'Sam Rivera');
  static const work = EmailAddress('sam.rivera@northwind.example', 'Sam Rivera');
  static const fastmail = EmailAddress('sam@rivera.example', 'Sam Rivera');

  static const jordan = EmailAddress('jordan.lee@example.com', 'Jordan Lee');
  static const mom = EmailAddress('ana.rivera@example.net', 'Ana Rivera');
  static const priya = EmailAddress('priya.nair@example.org', 'Priya Nair');
  static const elena = EmailAddress('elena.rossi@example.com', 'Elena Rossi');
  static const tom = EmailAddress('tom.becker@example.org', 'Tom Becker');
  static const marcus = EmailAddress('marcus.rivera@example.net', 'Marcus Rivera');

  static const dana = EmailAddress('dana.okafor@northwind.example', 'Dana Okafor');
  static const leo = EmailAddress('leo.martins@northwind.example', 'Leo Martins');
  static const aisha = EmailAddress('aisha.karimi@northwind.example', 'Aisha Karimi');
  static const ben = EmailAddress('ben.walsh@northwind.example', 'Ben Walsh');
  static const hana = EmailAddress('hana.sato@northwind.example', 'Hana Sato');
  static const it = EmailAddress('it-help@northwind.example', 'Northwind IT');
  static const peopleTeam = EmailAddress('people@northwind.example', 'Northwind People Team');
  static const tracker = EmailAddress('tracker@issues.northwind.example', 'Tracker');
  static const ci = EmailAddress('builds@ci.northwind.example', 'Northwind CI');
  static const olivia = EmailAddress('olivia.grant@fabrikam.example', 'Olivia Grant');
  static const calendar = EmailAddress('calendar@northwind.example', 'Calendar');

  static const felix = EmailAddress('felix@brandt.example', 'Felix Brandt');
  static const wren = EmailAddress('wren@abbott.example', 'Wren Abbott');
  static const kai = EmailAddress('kai.lindqvist@example.org', 'Kai Lindqvist');
  static const noor = EmailAddress('noor@haddad.example', 'Noor Haddad');
  static const gardenList = EmailAddress('open-garden@lists.opengarden.example', 'Open Garden');

  static const trailhead = EmailAddress('news@trailhead.example', 'Trailhead Outfitters');
  static const bank = EmailAddress('alerts@lumenbank.example', 'Lumen Bank');
  static const parcel = EmailAddress('noreply@parcelpost.example', 'Parcel Post');
  static const parcelFake = EmailAddress('service@parcelpost-notice.example.net', 'Parcel Post');
  static const rail = EmailAddress('tickets@northline.example', 'Northline Rail');
  static const library = EmailAddress('notices@citylibrary.example', 'City Library');
  static const run = EmailAddress('hello@striderun.example', 'Stride Run Club');
  static const security = EmailAddress('no-reply@accounts.gmail.example', 'Account Security');
  static const bookshop = EmailAddress('orders@cornerbookshop.example', 'Corner Bookshop');
  static const fieldNotes = EmailAddress('hello@fieldnotes.example', 'Field Notes Weekly');
  static const bookClub = EmailAddress('club@riversidebooks.example', 'Riverside Book Club');
  static const coffee = EmailAddress('receipts@harborcoffee.example', 'Harbor Coffee');
  static const registrar = EmailAddress('billing@namewell.example', 'Namewell Domains');
  static const backup = EmailAddress('reports@vaultbox.example', 'Vaultbox Backup');

  /// The senders the demo marks as VIP.
  static const vips = {'jordan.lee@example.com', 'ana.rivera@example.net', 'dana.okafor@northwind.example'};
}

/// Account ids of the demo mailbox.
abstract final class DemoAccounts {
  static const personal = 'personal';
  static const work = 'work';
  static const fastmail = 'fastmail';
}

/// Everything the demo repository starts with.
final class DemoSeed {
  DemoSeed._(this.now, int seed) : _random = Random(seed);

  /// Builds the demo mailbox relative to [now]. The same [seed] always gives
  /// the same mailbox.
  factory DemoSeed.build(DateTime now, {int seed = 7}) => DemoSeed._(now, seed).._build();

  final DateTime now;
  final Random _random;
  int _next = 1;

  final accounts = <MailAccount>[];
  final mailboxes = <Mailbox>[];

  /// Messages synced locally.
  final messages = <DemoMessage>[];

  /// Older messages per mailbox id, newest first, paged in by loadOlder.
  final older = <String, List<DemoMessage>>{};

  /// Messages only the "server" has (found by server search), per account.
  final serverOnly = <String, List<DemoMessage>>{};

  final _threadRefs = <String, List<String>>{};

  // Accounts and folders --------------------------------------------------------

  void _build() {
    _accounts();
    _personal();
    _work();
    _fastmail();
    _filler();
    _olderMail();
    _serverMail();
  }

  void _accounts() {
    accounts.addAll([
      MailAccount(
        id: DemoAccounts.personal,
        email: DemoPeople.personal.email,
        displayName: 'Personal',
        provider: ProviderKind.gmail,
        authKind: AuthKind.oauth2,
        incoming: const ServerConfig(protocol: ServerProtocol.imap, host: 'imap.gmail.com', port: 993),
        outgoing: const ServerConfig(protocol: ServerProtocol.smtp, host: 'smtp.gmail.com', port: 465),
        identities: const [
          Identity(id: 'personal/default', email: 'sam.rivera@gmail.example', name: 'Sam Rivera', signature: 'Sam'),
        ],
        colorIndex: 0,
      ),
      MailAccount(
        id: DemoAccounts.work,
        email: DemoPeople.work.email,
        displayName: 'Work',
        provider: ProviderKind.microsoft,
        authKind: AuthKind.oauth2,
        incoming: const ServerConfig(protocol: ServerProtocol.imap, host: 'outlook.office365.com', port: 993),
        outgoing: const ServerConfig(
          protocol: ServerProtocol.smtp,
          host: 'smtp.office365.com',
          port: 587,
          security: ConnectionSecurity.startTls,
        ),
        identities: const [
          Identity(
            id: 'work/default',
            email: 'sam.rivera@northwind.example',
            name: 'Sam Rivera',
            signature: 'Sam Rivera\nProduct Lead, Atlas · Northwind Labs',
          ),
          Identity(id: 'work/atlas', email: 'atlas-team@northwind.example', name: 'Atlas Team'),
        ],
        colorIndex: 2,
      ),
      MailAccount(
        id: DemoAccounts.fastmail,
        email: DemoPeople.fastmail.email,
        displayName: 'Fastmail',
        provider: ProviderKind.fastmail,
        authKind: AuthKind.password,
        incoming: const ServerConfig(protocol: ServerProtocol.imap, host: 'imap.fastmail.com', port: 993),
        outgoing: const ServerConfig(protocol: ServerProtocol.smtp, host: 'smtp.fastmail.com', port: 465),
        identities: const [
          Identity(id: 'fastmail/default', email: 'sam@rivera.example', name: 'Sam Rivera', signature: '— Sam'),
          Identity(id: 'fastmail/lists', email: 'lists@rivera.example', name: 'Sam Rivera'),
        ],
        colorIndex: 4,
      ),
    ]);

    void box(String account, String path, {MailboxRole role = MailboxRole.none, bool selectable = true}) {
      final slash = path.lastIndexOf('/');
      mailboxes.add(
        Mailbox(
          id: MailIds.mailbox(account, path),
          accountId: account,
          name: slash < 0 ? (path == 'INBOX' ? 'Inbox' : path) : path.substring(slash + 1),
          path: path,
          role: role,
          parentId: slash < 0 ? null : MailIds.mailbox(account, path.substring(0, slash)),
          isSelectable: selectable,
          sortOrder: mailboxes.length,
        ),
      );
    }

    const p = DemoAccounts.personal;
    box(p, 'INBOX', role: MailboxRole.inbox);
    box(p, '[Gmail]', selectable: false);
    box(p, '[Gmail]/Drafts', role: MailboxRole.drafts);
    box(p, '[Gmail]/Sent Mail', role: MailboxRole.sent);
    box(p, '[Gmail]/All Mail', role: MailboxRole.all);
    box(p, '[Gmail]/Spam', role: MailboxRole.junk);
    box(p, '[Gmail]/Trash', role: MailboxRole.trash);
    box(p, 'Family');
    box(p, 'Receipts');
    box(p, 'Travel');
    box(p, 'Travel/Japan 2025');
    box(p, 'Travel/Lisbon 2026');

    const w = DemoAccounts.work;
    box(w, 'INBOX', role: MailboxRole.inbox);
    box(w, 'Drafts', role: MailboxRole.drafts);
    box(w, 'Sent Items', role: MailboxRole.sent);
    box(w, 'Archive', role: MailboxRole.archive);
    box(w, 'Junk Email', role: MailboxRole.junk);
    box(w, 'Deleted Items', role: MailboxRole.trash);
    box(w, 'Projects');
    box(w, 'Projects/Atlas');
    box(w, 'Projects/Atlas/Design Reviews');
    box(w, 'Projects/Beacon');
    box(w, 'Team');
    box(w, 'Notifications');

    const f = DemoAccounts.fastmail;
    box(f, 'INBOX', role: MailboxRole.inbox);
    box(f, 'Drafts', role: MailboxRole.drafts);
    box(f, 'Sent', role: MailboxRole.sent);
    box(f, 'Archive', role: MailboxRole.archive);
    box(f, 'Spam', role: MailboxRole.junk);
    box(f, 'Trash', role: MailboxRole.trash);
    box(f, 'Lists');
    box(f, 'Lists/Open Garden');
    box(f, 'Newsletters');
    box(f, 'Receipts');
  }

  // Helpers ---------------------------------------------------------------------

  /// A time [daysAgo] calendar days back at [hour]:[minute]; today's times
  /// that would lie in the future are pulled into the past.
  DateTime at(int daysAgo, int hour, [int minute = 0]) {
    final t = DateTime(now.year, now.month, now.day - daysAgo, hour, minute);
    if (!t.isAfter(now)) return t;
    return now.subtract(Duration(minutes: 3 + (hour * 13 + minute) % 170));
  }

  DateTime minutesAgo(int minutes) => now.subtract(Duration(minutes: minutes));

  EmailAddress _me(String account) => switch (account) {
    DemoAccounts.work => DemoPeople.work,
    DemoAccounts.fastmail => DemoPeople.fastmail,
    _ => DemoPeople.personal,
  };

  /// Adds a message. [thread] links messages of one conversation (Message-ID,
  /// In-Reply-To, References). [into] picks the pool: local by default.
  DemoMessage add({
    required String account,
    required String box,
    required DateTime at,
    required EmailAddress from,
    required String subject,
    List<EmailAddress>? to,
    List<EmailAddress> cc = const [],
    String? text,
    String? html,
    bool isFlowed = false,
    bool unread = false,
    bool flagged = false,
    bool answered = false,
    bool forwarded = false,
    Set<String> tags = const {},
    String? thread,
    List<DemoAttachment> attachments = const [],
    List<(String, String)> headers = const [],
    bool authenticationFails = false,
    List<DemoMessage>? into,
  }) {
    final n = _next++;
    final domain = from.domain.isEmpty ? 'example.com' : from.domain;
    final messageId = '${thread ?? 'm'}.$n.${at.millisecondsSinceEpoch.toRadixString(36)}@$domain';
    final refs = thread == null ? const <String>[] : (_threadRefs[thread] ??= []);
    final keywords = <String>{
      if (!unread) Keywords.seen,
      if (flagged) Keywords.flagged,
      if (answered) Keywords.answered,
      if (forwarded) Keywords.forwarded,
      ...tags,
    };
    final mailboxId = MailIds.mailbox(account, box);
    final role = mailboxes.firstWhere((m) => m.id == mailboxId).role;
    if (role == MailboxRole.drafts) keywords.addAll({Keywords.draft, Keywords.seen});
    if (role == MailboxRole.sent) keywords.add(Keywords.seen);
    // Like real clients, preview the HTML part when there is one (preheaders included).
    final body = html != null ? htmlToPreviewText(html) : text ?? '';
    final summary = EmailSummary(
      id: MailIds.jmapEmail(account, 'M$n'),
      accountId: account,
      mailboxId: mailboxId,
      receivedAt: at,
      sentAt: at.subtract(Duration(seconds: 20 + n % 90)),
      threadId: thread == null ? 'T$n' : 'T-$account-$thread',
      messageIdHeader: messageId,
      inReplyTo: refs.isEmpty ? null : refs.last,
      references: List.of(refs),
      from: [from],
      to: to ?? [_me(account)],
      cc: cc,
      subject: subject,
      preview: makePreview(body),
      size: (html?.length ?? 0) + (text?.length ?? 0) + 1800 + attachments.fold(0, (s, a) => s + a.attachment.size),
      keywords: keywords,
      hasAttachment: attachments.any((a) => !a.attachment.isInline),
    );
    if (thread != null) refs.add(messageId);
    final message = DemoMessage(
      summary: summary,
      html: html,
      text: text,
      isFlowed: isFlowed,
      attachments: attachments,
      extraHeaders: headers,
      authenticationFails: authenticationFails,
    );
    (into ?? messages).add(message);
    return message;
  }

  static DemoAttachment pdf(String partId, String name, String title, {int size = 184320}) => DemoAttachment(
    Attachment(partId: partId, mimeType: 'application/pdf', filename: name, size: size),
    generate: () => tinyPdf(title),
  );

  static DemoAttachment inlineImage(String partId, String cid, String asset, String name, int size) => DemoAttachment(
    Attachment(
      partId: partId,
      mimeType: asset.endsWith('.png') ? 'image/png' : 'image/jpeg',
      filename: name,
      size: size,
      contentId: cid,
      isInline: true,
    ),
    asset: asset,
  );

  static DemoAttachment calendarInvite(String partId, String summary, DateTime start) => DemoAttachment(
    Attachment(partId: partId, mimeType: 'text/calendar', filename: 'invite.ics', size: 1240),
    generate: () => calendarFile(summary, start),
  );

  static DemoAttachment document(String partId, String name, String mime, int size) => DemoAttachment(
    Attachment(partId: partId, mimeType: mime, filename: name, size: size),
    generate: () => Uint8List.fromList(List.generate(512, (i) => (i * 31 + 7) % 256)),
  );

  static const _listHeaders = [
    ('List-Id', 'Open Garden development <open-garden.lists.opengarden.example>'),
    ('List-Post', '<mailto:open-garden@lists.opengarden.example>'),
    ('List-Unsubscribe', '<https://lists.opengarden.example/options/open-garden>'),
    ('Precedence', 'list'),
  ];

  static List<(String, String)> _newsletterHeaders(String domain) => [
    ('List-Unsubscribe', '<https://$domain/unsubscribe?u=sam>, <mailto:unsubscribe@$domain>'),
    ('List-Unsubscribe-Post', 'List-Unsubscribe=One-Click'),
    ('Precedence', 'bulk'),
  ];

  // Personal (Gmail) ---------------------------------------------------------------

  void _personal() {
    const a = DemoAccounts.personal;
    const inbox = 'INBOX';
    const sent = '[Gmail]/Sent Mail';
    const allMail = '[Gmail]/All Mail';
    final p = DemoPeople.personal;

    // The long conversation: nine messages over ten days.
    const lisbon = 'lisbon';
    final crew = [DemoPeople.priya, DemoPeople.elena, DemoPeople.tom, DemoPeople.jordan];
    List<EmailAddress> others(EmailAddress from) => [p, ...crew.where((c) => c != from)];
    add(
      account: a,
      box: allMail,
      at: at(11, 20, 14),
      from: DemoPeople.priya,
      to: [p, DemoPeople.elena, DemoPeople.tom, DemoPeople.jordan],
      subject: 'Lisbon in November?',
      text:
          'Okay, hear me out: Lisbon, long weekend in November. Flights are cheap if we go Thursday to Monday, '
          'and Elena knows a place in Alfama with a terrace.\n\nWho is in? Reply before Friday and I will start a spreadsheet.\n\nPriya',
      thread: lisbon,
      tags: {Keywords.label3},
    );
    add(
      account: a,
      box: allMail,
      at: at(11, 21, 2),
      from: DemoPeople.elena,
      to: others(DemoPeople.elena),
      subject: 'Re: Lisbon in November?',
      text:
          'In!! The terrace place is Casa do Largo, they have two rooms and a sofa bed. I can ask about the 13th–17th.\n\n'
          '> Who is in? Reply before Friday and I will start a spreadsheet.\n\nElena',
      thread: lisbon,
      tags: {Keywords.label3},
    );
    add(
      account: a,
      box: sent,
      at: at(10, 8, 40),
      from: p,
      to: others(p),
      subject: 'Re: Lisbon in November?',
      text:
          'Count me in. I can do the 13th–17th, but I have to be back for a Monday afternoon meeting, so an early '
          'flight on the 17th works best.\n\nSam',
      thread: lisbon,
    );
    add(
      account: a,
      box: allMail,
      at: at(10, 12, 5),
      from: DemoPeople.tom,
      to: others(DemoPeople.tom),
      subject: 'Re: Lisbon in November?',
      text: "I'm in if we can do one day trip to Sintra. Non-negotiable. I'll bring the good camera.\n\nTom",
      thread: lisbon,
    );
    add(
      account: a,
      box: allMail,
      at: at(9, 18, 30),
      from: DemoPeople.jordan,
      to: others(DemoPeople.jordan),
      subject: 'Re: Lisbon in November?',
      text: 'Yes yes yes. Sintra on Saturday, pastéis de nata every other hour. I can book the airport transfer.',
      thread: lisbon,
    );
    add(
      account: a,
      box: allMail,
      at: at(7, 9, 15),
      from: DemoPeople.priya,
      to: others(DemoPeople.priya),
      subject: 'Re: Lisbon in November?',
      text:
          'Spreadsheet is up — flights, rooms and who pays for what. Flights Thursday 07:10 are \$118 return right now. '
          "Let's book by Sunday before they go up.\n\nPriya",
      thread: lisbon,
      tags: {Keywords.label3},
    );
    add(
      account: a,
      box: sent,
      at: at(6, 19, 50),
      from: p,
      to: others(p),
      subject: 'Re: Lisbon in November?',
      text: 'Booked! Confirmation is in the spreadsheet. Elena, did Casa do Largo get back to you?\n\nSam',
      thread: lisbon,
    );
    add(
      account: a,
      box: inbox,
      at: at(3, 22, 10),
      from: DemoPeople.elena,
      to: others(DemoPeople.elena),
      subject: 'Re: Lisbon in November?',
      text:
          'They did — both rooms are ours, sofa bed too. Deposit is €60 each, I paid it, settle up whenever. '
          'They also recommended a fado place two streets away.\n\nElena',
      thread: lisbon,
      tags: {Keywords.label3},
    );
    add(
      account: a,
      box: inbox,
      at: at(0, 8, 45),
      from: DemoPeople.tom,
      to: others(DemoPeople.tom),
      subject: 'Re: Lisbon in November?',
      text:
          'Train to Sintra is 40 minutes from Rossio, every 20 min. I made a little plan for Saturday, '
          'see below. Also: does anyone have a travel adapter I can borrow?\n\n'
          '09:00 train from Rossio\n10:00 Pena Palace (book tickets ahead!)\n13:00 lunch in the old town\n'
          '15:00 Quinta da Regaleira\n18:30 back to Lisbon\n\nTom',
      thread: lisbon,
      unread: true,
      tags: {Keywords.label3},
    );

    // Dinner thread with a VIP.
    add(
      account: a,
      box: inbox,
      at: at(1, 17, 5),
      from: DemoPeople.jordan,
      subject: 'Dinner Saturday?',
      text: 'Want to try the new Georgian place on Mill Road? They do khachapuri the size of your head.',
      thread: 'dinner',
    );
    add(
      account: a,
      box: sent,
      at: at(1, 17, 40),
      from: p,
      to: [DemoPeople.jordan],
      subject: 'Re: Dinner Saturday?',
      text: 'Obviously yes. 7:30? I can book.',
      thread: 'dinner',
    );
    add(
      account: a,
      box: inbox,
      at: minutesAgo(38),
      from: DemoPeople.jordan,
      subject: 'Re: Dinner Saturday?',
      text: '7:30 is perfect. Also I sent you the hike photos, check your inbox!',
      thread: 'dinner',
      unread: true,
    );

    // The photo carousel.
    add(
      account: a,
      box: inbox,
      at: minutesAgo(52),
      from: DemoPeople.jordan,
      subject: 'Photos from Sunday’s hike',
      html: hikePhotosHtml,
      text:
          'Hey!\n\nFinally got the photos off my camera. The light on the ridge was unreal — the second one is my '
          'favourite.\n\n[IMG_2187.jpg]\n[IMG_2191.jpg]\n[IMG_2203.jpg]\n[IMG_2219.jpg]\n\n'
          'Can you send me the one you took at the lookout? Mine are all slightly crooked.\n\nJ',
      unread: true,
      flagged: true,
      attachments: [
        inlineImage('2', 'photo-mountains@demo', 'assets/demo/photo_mountains.jpg', 'IMG_2187.jpg', 12272),
        inlineImage('3', 'photo-forest@demo', 'assets/demo/photo_forest.jpg', 'IMG_2191.jpg', 22093),
        inlineImage('4', 'photo-beach@demo', 'assets/demo/photo_beach.jpg', 'IMG_2203.jpg', 20156),
        inlineImage('5', 'photo-city@demo', 'assets/demo/photo_city.jpg', 'IMG_2219.jpg', 52489),
      ],
    );

    // Marketing newsletter with preheader and tracking pixel.
    add(
      account: a,
      box: inbox,
      at: at(0, 6, 2),
      from: DemoPeople.trailhead,
      subject: 'Members: 20% off layers + the autumn layering guide',
      html: trailheadNewsletterHtml,
      unread: true,
      tags: {Keywords.label5},
      headers: _newsletterHeaders('trailhead.example'),
      attachments: [
        inlineImage('2', 'trailhead-logo@demo', 'assets/demo/trailhead_logo.png', 'logo.png', 2145),
        inlineImage('3', 'trailhead-hero@demo', 'assets/demo/trailhead_hero.jpg', 'hero.jpg', 10457),
        inlineImage('4', 'product-jacket@demo', 'assets/demo/product_jacket.jpg', 'jacket.jpg', 3647),
        inlineImage('5', 'product-pack@demo', 'assets/demo/product_pack.jpg', 'pack.jpg', 4309),
      ],
    );

    // The deceptive link.
    add(
      account: a,
      box: inbox,
      at: at(0, 7, 31),
      from: DemoPeople.parcelFake,
      subject: 'Action required: your parcel PP-88213-US could not be delivered',
      html: parcelPhishHtml,
      unread: true,
      authenticationFails: true,
    );

    // Mom: VIP, plain text with a quote, and a photo attachment.
    add(
      account: a,
      box: 'Family',
      at: at(5, 10, 12),
      from: DemoPeople.mom,
      subject: 'Grandpa’s birthday photo',
      text: momTextWithQuote,
      attachments: [
        const DemoAttachment(
          Attachment(partId: '2', mimeType: 'image/jpeg', filename: 'IMG_2041.jpg', size: 22093),
          asset: 'assets/demo/photo_forest.jpg',
        ),
      ],
    );
    add(
      account: a,
      box: inbox,
      at: at(2, 19, 22),
      from: DemoPeople.mom,
      subject: 'Lemon cake recipe (again!)',
      text:
          'In case the last one got lost:\n\n200 g butter, soft\n200 g sugar\n4 eggs\n250 g flour\n2 tsp baking powder\n'
          'Zest and juice of 2 lemons\n\nBake 45 minutes at 175°C. Drizzle with lemon and icing sugar while warm. '
          'Call me Sunday?\n\nLove, Mom',
      flagged: true,
      tags: {Keywords.label4},
    );
    add(
      account: a,
      box: inbox,
      at: at(4, 13, 0),
      from: DemoPeople.marcus,
      subject: 'Moving day — can you help on the 25th?',
      text:
          "Hey, we finally got the keys! Moving on the 25th. I've got a van from 9. Pizza and eternal gratitude "
          'on offer. Bring gloves.\n\nM',
      answered: true,
    );

    // Travel.
    add(
      account: a,
      box: 'Travel/Lisbon 2026',
      at: at(6, 20, 3),
      from: DemoPeople.rail,
      subject: 'Your e-ticket: Riverside → Airport, 13 Nov',
      text:
          'Booking reference: NL-7Q4K2\n\nThursday 13 November\nRiverside 05:12 → Airport 05:58\nCoach 4, seat 61\n\n'
          'Your ticket is attached. Show it on your phone or print it.',
      attachments: [pdf('2', 'Ticket-NL-7Q4K2.pdf', 'Northline Rail e-ticket NL-7Q4K2', size: 94210)],
      flagged: true,
    );
    add(
      account: a,
      box: 'Travel/Japan 2025',
      at: at(38, 9, 30),
      from: DemoPeople.priya,
      subject: 'Kyoto photo album',
      text: 'Finally made the album! It only took eleven months. The moss garden ones came out so well.',
    );

    add(
      account: a,
      box: inbox,
      at: at(1, 9, 3),
      from: DemoPeople.security,
      subject: 'Security alert: new sign-in on Pixel 9',
      text:
          'Your account sam.rivera@gmail.example was just used to sign in on a new device.\n\nPixel 9 · Riverside\n\n'
          "If this was you, you don't need to do anything. If not, we'll help you secure your account.",
    );
    add(
      account: a,
      box: inbox,
      at: at(2, 8, 15),
      from: DemoPeople.bank,
      subject: 'Your October statement is ready',
      text:
          'Your statement for the account ending 0921 is ready to view in online banking.\n\n'
          'Closing balance: \$3,482.17\nPayment due: 28 October\n\nLumen Bank will never ask for your password by email.',
      tags: {Keywords.label1},
    );
    add(
      account: a,
      box: 'Receipts',
      at: at(12, 14, 26),
      from: DemoPeople.coffee,
      to: [p],
      subject: 'Your receipt from Harbor Coffee',
      text: 'Flat white  \$4.20\nAlmond croissant  \$3.80\n\nTotal  \$8.00\nVisa ···· 4417\n\nThanks for stopping by!',
    );
  }

  // Work (Microsoft 365) ------------------------------------------------------------------

  void _work() {
    const a = DemoAccounts.work;
    const inbox = 'INBOX';
    const sent = 'Sent Items';
    final me = DemoPeople.work;

    const roadmap = 'roadmap';
    add(
      account: a,
      box: inbox,
      at: at(4, 9, 2),
      from: DemoPeople.dana,
      to: [me, DemoPeople.leo, DemoPeople.aisha],
      subject: 'Atlas Q4 roadmap review',
      text:
          'Hi all,\n\nAttached is the draft Q4 roadmap. Before Thursday’s review I need each of you to sanity-check '
          'the dates for your area. In particular:\n\n- Sam: offline mode — is mid-November still realistic?\n'
          '- Leo: sync engine rewrite, phase 1\n- Aisha: the onboarding redesign\n\nThanks,\nDana',
      thread: roadmap,
      tags: {Keywords.label1, Keywords.label2},
      attachments: [pdf('2', 'Atlas_Q4_Roadmap_draft.pdf', 'Atlas Q4 roadmap (draft)', size: 412004)],
    );
    add(
      account: a,
      box: inbox,
      at: at(4, 11, 40),
      from: DemoPeople.leo,
      to: [DemoPeople.dana, me, DemoPeople.aisha],
      subject: 'RE: Atlas Q4 roadmap review',
      text:
          'Sync phase 1 is fine for the 21st. Phase 2 depends on the storage migration, so I would mark it '
          '"tentative".\n\nLeo',
      thread: roadmap,
      tags: {Keywords.label2},
    );
    add(
      account: a,
      box: sent,
      at: at(3, 10, 5),
      from: me,
      to: [DemoPeople.dana, DemoPeople.leo, DemoPeople.aisha],
      subject: 'RE: Atlas Q4 roadmap review',
      text:
          'Offline mode: mid-November holds if we cut conflict resolution for attachments to a v2. '
          'I added a note in the doc. Happy to walk through it Thursday.\n\nSam',
      thread: roadmap,
    );
    add(
      account: a,
      box: inbox,
      at: at(2, 16, 18),
      from: DemoPeople.aisha,
      to: [DemoPeople.dana, me, DemoPeople.leo],
      subject: 'RE: Atlas Q4 roadmap review',
      text:
          "Onboarding is on track. Usability round 2 is next week; I'll share the clips. One risk: the illustrations "
          'are still with the agency.\n\nAisha',
      thread: roadmap,
      tags: {Keywords.label2},
    );
    add(
      account: a,
      box: inbox,
      at: minutesAgo(95),
      from: DemoPeople.dana,
      to: [me, DemoPeople.leo, DemoPeople.aisha],
      subject: 'RE: Atlas Q4 roadmap review',
      text:
          'Thanks all, this is great. Final version attached — I moved sync phase 2 to "tentative" and split '
          'offline mode as Sam suggested. Review stays Thursday 14:00.\n\nDana',
      thread: roadmap,
      unread: true,
      flagged: true,
      tags: {Keywords.label1, Keywords.label2},
      attachments: [pdf('2', 'Atlas_Q4_Roadmap_v3.pdf', 'Atlas Q4 roadmap v3', size: 436210)],
    );

    // Outlook-style message with fixed widths and tiny fonts.
    add(
      account: a,
      box: inbox,
      at: at(1, 15, 47),
      from: DemoPeople.olivia,
      subject: 'RE: Statement of work – phase 2 (revised pricing)',
      html: outlookSowHtml,
      tags: {Keywords.label4},
      flagged: true,
      headers: const [('X-Mailer', 'Microsoft Outlook 16.0'), ('Thread-Topic', 'Statement of work – phase 2')],
    );

    const offsite = 'offsite';
    add(
      account: a,
      box: 'Team',
      at: at(8, 10, 0),
      from: DemoPeople.hana,
      to: [me, DemoPeople.ben, DemoPeople.leo, DemoPeople.aisha],
      subject: 'Team offsite — logistics',
      text:
          'Hi team! Offsite is confirmed for the 6th at the Old Mill. Agenda attached. Please fill in the dietary '
          'form by Friday.\n\nHana',
      thread: offsite,
      attachments: [
        document(
          '2',
          'Offsite_agenda.docx',
          'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
          48211,
        ),
      ],
    );
    add(
      account: a,
      box: 'Team',
      at: at(8, 11, 20),
      from: DemoPeople.ben,
      to: [DemoPeople.hana, me, DemoPeople.leo, DemoPeople.aisha],
      subject: 'RE: Team offsite — logistics',
      text: 'Is there parking at the Old Mill or should we carpool?',
      thread: offsite,
    );
    add(
      account: a,
      box: 'Team',
      at: at(7, 9, 5),
      from: DemoPeople.hana,
      to: [DemoPeople.ben, me, DemoPeople.leo, DemoPeople.aisha],
      subject: 'RE: Team offsite — logistics',
      text: 'Limited parking — carpool sheet is in the channel. Sam, you offered seats last time?',
      thread: offsite,
      unread: true,
    );

    add(
      account: a,
      box: inbox,
      at: at(0, 9, 12),
      from: DemoPeople.calendar,
      subject: 'Invitation: Atlas design review @ Thursday 14:00 – 15:00',
      text:
          'Dana Okafor has invited you to Atlas design review.\n\nThursday 14:00 – 15:00\nRoom: Lighthouse (3rd floor) '
          'and online\n\nAccept · Tentative · Decline',
      unread: true,
      attachments: [calendarInvite('2', 'Atlas design review', DateTime(now.year, now.month, now.day + 2, 14))],
    );
    add(
      account: a,
      box: inbox,
      at: at(0, 10, 30),
      from: DemoPeople.ben,
      subject: 'Quick question about the export API',
      text:
          'Hey Sam, quick one: does the export endpoint paginate by cursor or by page number? The docs say both. '
          'Customer is asking.\n\nBen',
      unread: true,
    );
    add(
      account: a,
      box: inbox,
      at: at(1, 12, 2),
      from: DemoPeople.leo,
      subject: 'Lunch?',
      text: 'Ramen place at 12:30? Hana is in too.',
      answered: true,
    );
    add(
      account: a,
      box: inbox,
      at: at(3, 8, 0),
      from: DemoPeople.it,
      subject: 'Scheduled maintenance this Saturday 22:00–02:00',
      text:
          'VPN and the build farm will be unavailable on Saturday between 22:00 and 02:00 while we upgrade the '
          'network core. No action needed.\n\nNorthwind IT',
    );
    add(
      account: a,
      box: inbox,
      at: at(5, 9, 0),
      from: DemoPeople.peopleTeam,
      subject: 'Open enrollment closes Friday',
      text:
          'Reminder: benefits open enrollment closes this Friday at 17:00. If you do nothing, your current '
          'choices roll over.\n\nNorthwind People Team',
      tags: {Keywords.label4},
    );
    add(
      account: a,
      box: 'Projects/Atlas/Design Reviews',
      at: at(15, 15, 0),
      from: DemoPeople.aisha,
      subject: 'Design review notes: onboarding v2',
      text:
          'Notes from today:\n\n1. Drop the carousel on step 2, nobody swipes it.\n2. Account picker: show provider '
          'logos.\n3. Error copy needs a pass — "Authentication failed" is not helpful.\n\nNext review in two weeks.',
    );
    add(
      account: a,
      box: 'Projects/Beacon',
      at: at(26, 11, 0),
      from: DemoPeople.hana,
      subject: 'Beacon retro — what went well',
      text: 'Thanks for a great retro. Summary: shipping weekly worked, the on-call rotation did not. Proposal next week.',
    );
    add(
      account: a,
      box: 'Drafts',
      at: at(1, 18, 2),
      from: me,
      to: [DemoPeople.dana],
      subject: 'Hiring plan for Q1',
      text: 'Dana, here is a first pass at the Q1 hiring plan. Two engineers for sync, one designer for',
    );
    add(
      account: a,
      box: 'Junk Email',
      at: at(2, 3, 14),
      from: const EmailAddress('promo@supplements-deal.example.net', 'Health Deals'),
      subject: 'You have been selected!!!',
      text: 'Congratulations, you have been selected for an exclusive offer. Click now.',
      tags: {Keywords.junk},
    );
  }

  // Fastmail ---------------------------------------------------------------------------

  void _fastmail() {
    const a = DemoAccounts.fastmail;
    const inbox = 'INBOX';
    final me = DemoPeople.fastmail;

    add(
      account: a,
      box: inbox,
      at: at(0, 11, 4),
      from: DemoPeople.felix,
      subject: 'Re: the closet server',
      text: felixFlowedText,
      isFlowed: true,
      unread: true,
      thread: 'closet',
      headers: const [('User-Agent', 'Mutt/2.2.12 (2023-09-09)')],
    );
    add(
      account: a,
      box: inbox,
      at: at(1, 18, 30),
      from: DemoPeople.bookshop,
      subject: 'Order #10482 confirmed — ready for pickup Thursday',
      html: bookshopReceiptHtml,
      attachments: [
        inlineImage('2', 'bookshop-logo@demo', 'assets/demo/bookshop_logo.png', 'logo.png', 3091),
        pdf('3', 'Invoice-10482.pdf', 'Corner Bookshop invoice 10482', size: 61234),
      ],
    );
    add(
      account: a,
      box: inbox,
      at: at(2, 7, 0),
      from: DemoPeople.bookClub,
      subject: 'November pick: The Lantern Keepers',
      html: bookClubHtml,
      unread: true,
    );

    const manifest = 'manifest';
    const garden = 'Lists/Open Garden';
    add(
      account: a,
      box: garden,
      at: at(3, 21, 40),
      from: DemoPeople.wren,
      to: [DemoPeople.gardenList],
      subject: '[open-garden] RFC: plugin manifest v2',
      text: gardenListLongText,
      thread: manifest,
      headers: _listHeaders,
    );
    add(
      account: a,
      box: garden,
      at: at(2, 9, 12),
      from: DemoPeople.kai,
      to: [DemoPeople.gardenList],
      subject: 'Re: [open-garden] RFC: plugin manifest v2',
      text:
          '> Should "beds = ask" be the default, or "all"?\n\nAsk, please. One prompt per bed is not noisy if we '
          'remember the answer. And "beds" is fine, people like it.\n\nKai',
      thread: manifest,
      headers: _listHeaders,
    );
    add(
      account: a,
      box: garden,
      at: at(1, 22, 5),
      from: DemoPeople.noor,
      to: [DemoPeople.gardenList],
      subject: 'Re: [open-garden] RFC: plugin manifest v2',
      text:
          '> Do we sign manifests?\n\nNot without signing the bundle too. Let us do both in 3.6 and keep this '
          'RFC about the format.\n\nNoor',
      thread: manifest,
      unread: true,
      headers: _listHeaders,
    );
    add(
      account: a,
      box: 'Sent',
      at: at(1, 23, 0),
      from: const EmailAddress('lists@rivera.example', 'Sam Rivera'),
      to: [DemoPeople.gardenList],
      subject: 'Re: [open-garden] RFC: plugin manifest v2',
      text: '+1 to "ask" as the default. Could the migrate tool print which hooks it could not map?\n\nSam',
      thread: manifest,
      headers: _listHeaders,
    );
    add(
      account: a,
      box: 'Receipts',
      at: at(9, 6, 40),
      from: DemoPeople.registrar,
      subject: 'rivera.example renews in 30 days',
      text: 'Your domain rivera.example renews automatically on 3 November for \$14.00. Nothing to do.',
    );
    add(
      account: a,
      box: inbox,
      at: at(6, 3, 0),
      from: DemoPeople.backup,
      subject: 'Monthly backup report: 3 devices, all healthy',
      text:
          'closet-server  last backup 2h ago  ✓\nlaptop        last backup 1d ago  ✓\nphone         last backup 3h ago  ✓\n\n'
          'Storage used: 412 GB of 1 TB.',
    );
    add(
      account: a,
      box: 'Drafts',
      at: at(4, 22, 15),
      from: me,
      to: [DemoPeople.felix],
      subject: 'Repair café',
      text: 'Yes! I will bring the toaster. Do you know if they',
    );
    add(
      account: a,
      box: 'Spam',
      at: at(5, 2, 2),
      from: const EmailAddress('winner@lottery-intl.example.net', 'International Lottery'),
      subject: 'Claim your prize of \$1,000,000 now',
      text: 'Your email was selected in our annual draw. Send your bank details to claim.',
      tags: {Keywords.junk},
    );
  }

  // Bulk mail (notifications, newsletters, small talk) -----------------------------------

  T _pick<T>(List<T> list) => list[_random.nextInt(list.length)];

  /// A spread of days over the last six weeks, newest first.
  List<int> _days(int count, {int maxDays = 42}) {
    final days = [for (var i = 0; i < count; i++) _random.nextInt(maxDays)];
    days.sort();
    return days;
  }

  void _filler() {
    const p = DemoAccounts.personal;
    const w = DemoAccounts.work;
    const f = DemoAccounts.fastmail;

    // Personal.
    final grocers = ['Green Grocer', 'Mill Road Bakery', 'Riverside Pharmacy', 'Northline Rail', 'Cinema Paradiso'];
    for (final d in _days(7)) {
      final amount = (8 + _random.nextInt(80)) + _random.nextInt(100) / 100;
      final shop = _pick(grocers);
      add(
        account: p,
        box: d < 10 ? 'INBOX' : '[Gmail]/All Mail',
        at: at(d + 1, 8 + _random.nextInt(12), _random.nextInt(60)),
        from: DemoPeople.bank,
        subject: 'Card payment of \$${amount.toStringAsFixed(2)} at $shop',
        text:
            'A payment of \$${amount.toStringAsFixed(2)} was made with your card ending 4417 at $shop.\n\n'
            "If you don't recognise it, freeze your card in the app.",
      );
    }
    final parcels = ['running shoes', 'phone case', 'bike light', 'book order', 'coffee beans'];
    for (final d in _days(4)) {
      final item = _pick(parcels);
      final code = 'PP-${40000 + _random.nextInt(50000)}-US';
      add(
        account: p,
        box: d < 7 ? 'INBOX' : '[Gmail]/All Mail',
        at: at(d + 1, 9 + _random.nextInt(9), _random.nextInt(60)),
        from: DemoPeople.parcel,
        subject: _random.nextBool() ? 'Your parcel is on its way ($code)' : 'Delivered: your $item',
        text:
            'Parcel $code with your $item is on its way and should arrive in 1–2 days.\n\nTrack it at parcelpost.example.',
      );
    }
    final runs = [
      ('This week: Thursday tempo run', 'Tempo run Thursday at 6:30 pm from the boathouse. 8 km, three pace groups.'),
      (
        'Race day info: Riverside 10K',
        'Bib pickup Saturday 10–16 at the club. Start is 9:00 sharp, bag drop opens 8:00.',
      ),
      ('New winter kit is in', 'Members can order the new long-sleeve club top until the 30th.'),
      ('Sunday long run route', 'This Sunday: 18 km along the canal, coffee stop at km 11.'),
    ];
    for (final (i, d) in _days(4).indexed) {
      final (subject, text) = runs[i % runs.length];
      add(
        account: p,
        box: 'INBOX',
        at: at(d + 1, 7, 15),
        from: DemoPeople.run,
        subject: subject,
        text: '$text\n\nSee you out there!\nStride Run Club',
        unread: d < 4 && i.isEven,
        headers: _newsletterHeaders('striderun.example'),
      );
    }
    for (final d in _days(3)) {
      add(
        account: p,
        box: 'INBOX',
        at: at(d + 2, 10, 5),
        from: DemoPeople.library,
        subject: _random.nextBool() ? 'Reminder: 2 items due soon' : 'Your hold is ready for pickup',
        text:
            'Hello Sam,\n\nThe Overstory and A Field Guide to Getting Lost are due on the 18th. You can renew them '
            'online twice.\n\nCity Library',
      );
    }
    final friendly = [
      (
        DemoPeople.elena,
        'Recipe you asked for',
        'The tomato tart! Use the puff pastry from the deli, not the frozen one.',
      ),
      (
        DemoPeople.tom,
        'Board games Friday?',
        'Bringing the new one with the trains. It takes 3 hours, you have been warned.',
      ),
      (DemoPeople.priya, 'That podcast', 'The episode about the lighthouse keepers. You will love it.'),
      (DemoPeople.marcus, 'Mum’s birthday present', 'Shall we go halves on the garden bench? I found one that folds.'),
      (DemoPeople.jordan, 'Concert tickets', 'Got two for the 14th! Row F. You owe me a drink.'),
      (DemoPeople.elena, 'Plant swap', 'I have too many cuttings again. Want a pothos?'),
    ];
    for (final (i, d) in _days(friendly.length, maxDays: 40).indexed) {
      final (from, subject, text) = friendly[i];
      add(
        account: p,
        box: i.isEven ? 'INBOX' : '[Gmail]/All Mail',
        at: at(d + 2, 18 + _random.nextInt(4), _random.nextInt(60)),
        from: from,
        subject: subject,
        text: text,
        answered: _random.nextBool(),
        tags: i == 3 ? {Keywords.label4} : const {},
      );
    }
    for (final d in _days(3)) {
      add(
        account: p,
        box: 'Receipts',
        at: at(d + 3, 12, 40),
        from: DemoPeople.coffee,
        subject: 'Your receipt from Harbor Coffee',
        text: 'Oat latte  \$4.60\nCinnamon bun  \$3.40\n\nTotal  \$8.00\nVisa ···· 4417',
      );
    }

    // Work.
    final issues = [
      ('ATLAS-142', 'Sync engine stalls on large folders'),
      ('ATLAS-158', 'Offline queue loses order after restart'),
      ('ATLAS-163', 'Onboarding: provider logos are blurry on tablets'),
      ('ATLAS-171', 'Search results flicker while typing'),
      ('ATLAS-176', 'Crash when opening attachments over 25 MB'),
      ('ATLAS-180', 'Dark mode: unread dot has low contrast'),
    ];
    final events = ['commented', 'changed the status to In Review', 'assigned the issue to you', 'resolved the issue'];
    final devs = [DemoPeople.leo, DemoPeople.aisha, DemoPeople.ben, DemoPeople.hana];
    for (final d in _days(16, maxDays: 30)) {
      final (key, title) = _pick(issues);
      final dev = _pick(devs);
      final event = _pick(events);
      add(
        account: w,
        box: d < 3 ? 'INBOX' : 'Notifications',
        at: at(d, 9 + _random.nextInt(9), _random.nextInt(60)),
        from: DemoPeople.tracker,
        subject: '[$key] $title',
        text:
            '${dev.displayName} $event.\n\n'
            '${event == 'commented' ? '"Repro is reliable on the staging account with 40k messages. Looking at the batching now."\n\n' : ''}'
            'View $key in Tracker: https://tracker.northwind.example/browse/$key',
        unread: d < 2 && _random.nextBool(),
        tags: {Keywords.label2},
      );
    }
    for (final d in _days(6, maxDays: 25)) {
      final build = 1800 + _random.nextInt(60);
      final failed = _random.nextInt(3) == 0;
      add(
        account: w,
        box: 'Notifications',
        at: at(d, 11 + _random.nextInt(7), _random.nextInt(60)),
        from: DemoPeople.ci,
        subject: failed ? 'Build failed: atlas-app #$build' : 'Build fixed: atlas-app #$build',
        text: failed
            ? 'Build #$build failed on main.\n\nFailing step: integration-tests (3 failures)\nCommit: 7f3a2c1 by Leo Martins'
            : 'Build #$build is green again on main.',
      );
    }
    final colleagues = [
      (DemoPeople.hana, 'Slides for Thursday', 'Can you add one slide on offline mode? Two bullets is enough.'),
      (
        DemoPeople.aisha,
        'Usability clips',
        'Clips from round 2 are in the shared drive. Session 3 is the interesting one.',
      ),
      (
        DemoPeople.leo,
        'Storage migration plan',
        'First draft of the migration plan is up. Main risk is the FTS rebuild time.',
      ),
      (DemoPeople.ben, 'Customer call notes', 'Notes from the call with the Harbor team. They want shared mailboxes.'),
      (DemoPeople.dana, '1:1 agenda', 'For Monday: hiring plan, the offsite, and your Q1 goals. Anything to add?'),
      (DemoPeople.hana, 'Welcome lunch for Mateo', 'Mateo starts Monday! Lunch at 12:30, Northwind treats.'),
      (DemoPeople.peopleTeam, 'Reminder: submit your expenses', 'Expenses for October are due by the 5th.'),
      (DemoPeople.it, 'Your password expires in 7 days', 'Change it from the account portal before it expires.'),
    ];
    for (final (i, d) in _days(colleagues.length, maxDays: 38).indexed) {
      final (from, subject, text) = colleagues[i];
      add(
        account: w,
        box: d < 20 ? 'INBOX' : 'Archive',
        at: at(d + 1, 9 + _random.nextInt(8), _random.nextInt(60)),
        from: from,
        subject: subject,
        text: '$text\n\n${from.displayName.split(' ').first}',
        answered: from != DemoPeople.peopleTeam && from != DemoPeople.it && _random.nextBool(),
        flagged: i == 4,
        tags: from == DemoPeople.dana ? {Keywords.label1} : const {},
      );
    }
    for (final d in _days(5, maxDays: 30)) {
      add(
        account: w,
        box: 'Sent Items',
        at: at(d + 1, 10 + _random.nextInt(7), _random.nextInt(60)),
        from: DemoPeople.work,
        to: [_pick(devs)],
        subject: _pick([
          'Re: Storage migration plan',
          'Re: Usability clips',
          'Notes from the review',
          'Re: Customer call notes',
        ]),
        text: _pick([
          'Thanks — looks good. Two small comments inline in the doc.',
          'Agreed. Let us pick this up after standup.',
          'Sharing my notes from today. Main decision: we ship offline mode behind a flag first.',
        ]),
      );
    }

    // Fastmail.
    final listTopics = [
      (
        'Release 3.3.1 is out',
        DemoPeople.wren,
        'Bug-fix release: the humidity sensor driver no longer reports 0% after a reboot.',
      ),
      (
        'Frost alerts misfire in UTC+13',
        DemoPeople.kai,
        'Found it: the scheduler uses local midnight from the server, not the garden.',
      ),
      (
        'Docs sprint this weekend',
        DemoPeople.noor,
        'Join us on Saturday to rewrite the getting-started guide. Coffee is on me.',
      ),
      ('Raspberry Pi 5 support', DemoPeople.kai, 'The new GPIO library works with one patch. PR incoming.'),
      (
        'Meeting notes 14 Oct',
        DemoPeople.wren,
        'Attendees: 9. Decisions: 3.3.1 ships Friday; manifest RFC goes to the list.',
      ),
    ];
    for (final (i, d) in _days(10, maxDays: 40).indexed) {
      final (topic, from, text) = listTopics[i % listTopics.length];
      add(
        account: f,
        box: 'Lists/Open Garden',
        at: at(d + 1, 8 + _random.nextInt(14), _random.nextInt(60)),
        from: from,
        to: [DemoPeople.gardenList],
        subject: '${i >= listTopics.length ? 'Re: ' : ''}[open-garden] $topic',
        text:
            '$text\n\n-- \n${from.displayName}\n\n_______________________________________________\nopen-garden mailing list',
        unread: d < 3,
        headers: _listHeaders,
      );
    }
    for (final (i, d) in _days(6, maxDays: 42).indexed) {
      final issue = 46 - i;
      add(
        account: f,
        box: i == 0 ? 'INBOX' : 'Newsletters',
        at: at(d + 1, 6, 30),
        from: DemoPeople.fieldNotes,
        subject:
            'Field Notes #$issue: ${_pick(['Slow software', 'The case for paper maps', 'Repair, not replace', 'Small web, big ideas', 'Notes on attention', 'Winter light'])}',
        html:
            '<div style="max-width:560px;font-family:Georgia,serif;font-size:17px;line-height:1.6;color:#2b2b2b">'
            '<div style="display:none">Five links, one essay and a photo from the coast.</div>'
            '<h1 style="font-size:26px">Field Notes #$issue</h1>'
            '<p>Hello friends — this week I have been thinking about tools that stay out of the way. '
            'The best ones disappear: you notice the work, not the tool.</p>'
            '<p><b>Five links</b></p><ol><li>A tiny forum that has run since 2003</li><li>Why maps fold the way they do</li>'
            '<li>An ode to the paperclip</li><li>Repair cafés, counted</li><li>A slow radio station from the north</li></ol>'
            '<p>Until next week,<br>Mira</p>'
            '<img src="https://pixel.fieldnotes.example/open/$issue.gif" width="1" height="1" alt=""></div>',
        unread: d < 5,
        tags: {Keywords.label5},
        headers: _newsletterHeaders('fieldnotes.example'),
      );
    }
    final pals = [
      (DemoPeople.felix, 'Repair café on the 15th', 'Bring anything with a plug. The soldering station is back.'),
      (DemoPeople.noor, 'Coffee next week?', 'I am in town Tuesday and Wednesday. Same place as last time?'),
      (DemoPeople.kai, 'Seeds!', 'I saved too many tomato seeds again. Want some Black Krim?'),
    ];
    for (final (i, d) in _days(pals.length, maxDays: 30).indexed) {
      final (from, subject, text) = pals[i];
      add(
        account: f,
        box: i == 2 ? 'Archive' : 'INBOX',
        at: at(d + 2, 19, 10 + i * 7),
        from: from,
        subject: subject,
        text: text,
        answered: i != 1,
      );
    }
    for (final d in _days(2, maxDays: 40)) {
      add(
        account: f,
        box: 'Trash',
        at: at(d + 1, 12),
        from: DemoPeople.fieldNotes,
        subject: 'Your subscription is confirmed',
        text: 'Thanks for subscribing to Field Notes Weekly.',
      );
    }
  }

  // Older mail (loadOlder) and server-only mail (server search) ---------------------------

  void _olderMail() {
    final pools = {
      MailIds.mailbox(DemoAccounts.personal, 'INBOX'): [
        (DemoPeople.bank, 'Your September statement is ready', 'Your statement for the account ending 0921 is ready.'),
        (DemoPeople.jordan, 'Weekend plans?', 'Farmers market Saturday then the lake if it is sunny?'),
        (DemoPeople.run, 'Autumn half marathon plan', 'Twelve weeks, four runs a week. Plan attached in the app.'),
        (DemoPeople.mom, 'Garden photos', 'The roses came back! Dad says hello.'),
        (DemoPeople.library, 'Your hold is ready for pickup', 'Your hold is ready at the main branch until Friday.'),
        (DemoPeople.parcel, 'Delivered: your parcel', 'Your parcel was delivered to the front door at 14:02.'),
        (DemoPeople.priya, 'Japan photos, finally', 'I printed the Kyoto ones. Want copies?'),
      ],
      MailIds.mailbox(DemoAccounts.work, 'INBOX'): [
        (DemoPeople.dana, 'Q3 wrap-up', 'Thanks for a strong quarter. Highlights and lowlights in the doc.'),
        (DemoPeople.tracker, '[ATLAS-118] Login loop on SSO accounts', 'Resolved by Leo Martins.'),
        (DemoPeople.hana, 'Summer party photos', 'All the photos from the party are in the shared album.'),
        (DemoPeople.peopleTeam, 'Mid-year reviews', 'Self-reviews are due by the 15th.'),
        (DemoPeople.ci, 'Build fixed: atlas-app #1712', 'Build #1712 is green again on main.'),
        (DemoPeople.leo, 'Sync engine: design doc', 'Design doc for the sync rewrite. Comments welcome.'),
      ],
      MailIds.mailbox(DemoAccounts.fastmail, 'INBOX'): [
        (DemoPeople.felix, 'The radio lives!', 'It was a dry joint on the power board. Third time lucky.'),
        (DemoPeople.fieldNotes, 'Field Notes #39: On walking', 'Hello friends — a whole issue about walking.'),
        (DemoPeople.registrar, 'Payment received', 'Thanks, we received your payment for rivera.example.'),
        (DemoPeople.backup, 'Monthly backup report', 'All three devices backed up in the last 24 hours.'),
        (DemoPeople.kai, 'Greenhouse sensor wiring', 'Photos of the wiring as promised.'),
      ],
    };
    for (final MapEntry(key: mailboxId, value: templates) in pools.entries) {
      final (account, path) = MailIds.parseMailbox(mailboxId);
      final list = <DemoMessage>[];
      for (var i = 0; i < 24; i++) {
        final (from, subject, text) = templates[i % templates.length];
        add(
          account: account,
          box: path,
          at: at(43 + i * 2 + _random.nextInt(2), 8 + _random.nextInt(11), _random.nextInt(60)),
          from: from,
          subject: i < templates.length ? subject : '$subject (${_monthName(43 + i * 2)})',
          text: text,
          into: list,
        );
      }
      older[mailboxId] = list;
    }
  }

  String _monthName(int daysAgo) {
    const names = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
    return names[now.subtract(Duration(days: daysAgo)).month - 1];
  }

  void _serverMail() {
    final pools = {
      DemoAccounts.personal: (
        '[Gmail]/All Mail',
        [
          (
            DemoPeople.jordan,
            'Photos from the lake',
            'Here are the photos from the lake weekend. The one with the dog!',
          ),
          (
            DemoPeople.priya,
            'Japan trip: invoice for the ryokan',
            'Invoice for the ryokan is attached, split four ways.',
          ),
          (
            DemoPeople.elena,
            'Lisbon recommendations from last time',
            'The list from my 2023 trip: tascas, viewpoints, fado.',
          ),
          (DemoPeople.bank, 'Your annual statement', 'Your annual statement for last year is ready.'),
          (DemoPeople.mom, 'Recipe box', 'I typed up Grandma’s recipes. Lemon cake is on page 3.'),
          (DemoPeople.tom, 'Camera settings for night photos', 'ISO 1600, f/2.8, and a tripod. Trust me.'),
          (
            DemoPeople.marcus,
            'Flat viewing notes',
            'Notes from the three flats we saw, with the invoice from the agent.',
          ),
          (DemoPeople.rail, 'Your e-ticket: Riverside → Coast', 'Booking reference NL-2B8J1. Have a good trip.'),
          (DemoPeople.trailhead, 'Your order has shipped', 'Your Summit 28 L daypack is on its way.'),
        ],
      ),
      DemoAccounts.work: (
        'Archive',
        [
          (DemoPeople.dana, 'Atlas kickoff', 'Welcome to Atlas! Kickoff deck and meeting notes attached.'),
          (DemoPeople.olivia, 'Invoice INV-2291 for phase 1', 'Please find the invoice for phase 1 attached.'),
          (
            DemoPeople.leo,
            'Meeting notes: sync architecture',
            'Notes from the architecture meeting, with photos of the whiteboard.',
          ),
          (
            DemoPeople.aisha,
            'Onboarding research summary',
            'Summary of the 12 interviews, invoice from the agency attached.',
          ),
          (DemoPeople.hana, 'Offsite photos from last year', 'Photos from last year’s offsite, as requested.'),
          (
            DemoPeople.peopleTeam,
            'Your contract amendment',
            'Signed copy of your contract amendment for your records.',
          ),
          (DemoPeople.ben, 'Harbor customer meeting', 'Meeting summary and next steps for the Harbor account.'),
        ],
      ),
      DemoAccounts.fastmail: (
        'Archive',
        [
          (DemoPeople.felix, 'Old photos from the repair café', 'Found some photos from the first repair café, 2019.'),
          (DemoPeople.registrar, 'Invoice for rivera.example', 'Invoice NW-88213 for your domain renewal.'),
          (DemoPeople.wren, '[open-garden] Meeting notes from the 2024 summit', 'Notes and photos from the summit.'),
          (DemoPeople.bookshop, 'Order #9921 confirmed', 'Your order is ready for pickup. Invoice attached.'),
          (DemoPeople.noor, 'Trip to the coast', 'Photos from our trip to the coast last spring.'),
          (DemoPeople.kai, 'Seed swap meeting', 'Meeting at the library on Saturday. Bring labels.'),
        ],
      ),
    };
    for (final MapEntry(key: account, value: (path, templates)) in pools.entries) {
      final list = <DemoMessage>[];
      for (final (i, (from, subject, text)) in templates.indexed) {
        add(
          account: account,
          box: path,
          at: at(120 + i * 37 + _random.nextInt(20), 9 + _random.nextInt(9), _random.nextInt(60)),
          from: from,
          subject: subject,
          text: text,
          attachments: subject.toLowerCase().contains('invoice')
              ? [pdf('2', '${subject.split(' ').take(3).join('_')}.pdf', subject, size: 52000 + i * 1000)]
              : const [],
          into: list,
        );
      }
      serverOnly[account] = list;
    }
  }

  /// Templates for messages that "arrive" on refresh: (account, from, subject, text).
  static const incoming = [
    (DemoAccounts.personal, DemoPeople.jordan, 'Running 10 min late', 'Save me a seat! Traffic on the bridge.'),
    (
      DemoAccounts.personal,
      DemoPeople.parcel,
      'Out for delivery today',
      'Your parcel will arrive between 10:00 and 14:00.',
    ),
    (
      DemoAccounts.personal,
      DemoPeople.priya,
      'Flights are booked!',
      'All five of us on the 07:10. Lisbon here we come.',
    ),
    (
      DemoAccounts.personal,
      DemoPeople.mom,
      'Call tonight?',
      'Are you free after dinner? Nothing urgent, just want to chat.',
    ),
    (
      DemoAccounts.work,
      DemoPeople.tracker,
      '[ATLAS-182] Attachments fail on slow networks',
      'Ben Walsh assigned the issue to you.',
    ),
    (
      DemoAccounts.work,
      DemoPeople.dana,
      'Quick sync before the review?',
      'Five minutes before Thursday’s review? I have one question about offline mode.',
    ),
    (
      DemoAccounts.work,
      DemoPeople.hana,
      'Cake in the kitchen',
      'It is Leo’s birthday. Cake by the coffee machine, go go go.',
    ),
    (
      DemoAccounts.fastmail,
      DemoPeople.felix,
      'Radio update',
      'It works. It actually works. Bringing it to the café to show off.',
    ),
    (
      DemoAccounts.fastmail,
      DemoPeople.kai,
      '[open-garden] 3.3.2 release candidate',
      'RC1 is tagged. Please test on your gardens this week.',
    ),
  ];
}

/// Collapses whitespace into a list preview of at most 256 characters.
String makePreview(String text) {
  final collapsed = text
      .split('\n')
      // Quotes and their "On …, X wrote:" lines say nothing new.
      .where((l) => !l.trimLeft().startsWith('>') && !l.trimRight().endsWith('wrote:'))
      .join(' ')
      .replaceAll(RegExp(r'\s+'), ' ')
      .trim();
  return collapsed.length <= 256 ? collapsed : collapsed.substring(0, 256);
}

/// Rough HTML-to-text for previews and the text/plain alternative.
String htmlToPreviewText(String html) => html
    .replaceAll(RegExp(r'<(style|script|title)[^>]*>.*?</\1>', caseSensitive: false, dotAll: true), ' ')
    .replaceAll(RegExp(r'<br\s*/?>|</p>|</div>|</tr>|</h\d>|</li>', caseSensitive: false), '\n')
    .replaceAll(RegExp(r'<[^>]+>'), ' ')
    .replaceAll('&nbsp;', ' ')
    .replaceAll('&zwnj;', '')
    .replaceAll('&amp;', '&')
    .replaceAll('&mdash;', '—')
    .replaceAll('&#8212;', '—')
    .replaceAll('&lt;', '<')
    .replaceAll('&gt;', '>')
    .replaceAll(RegExp(r'[ \t]+'), ' ')
    .replaceAll(RegExp(r'\n\s*\n\s*\n+'), '\n\n')
    .trim();
