// Regenerates lib/src/smime/mozilla_roots.dart from NSS's certdata.txt:
// the root certificates Mozilla trusts for email (CKA_TRUST_EMAIL_PROTECTION
// CKT_NSS_TRUSTED_DELEGATOR), the ones Thunderbird checks S/MIME against.
//
//   dart run tool/update_mozilla_roots.dart [path/to/certdata.txt]
//
// Without a path it downloads the current file from mozilla-central.
// ignore_for_file: avoid_print
import 'dart:convert';
import 'dart:io';
import 'dart:typed_data';

import 'package:pointycastle/digests/sha1.dart';

const _source = 'https://hg-edge.mozilla.org/mozilla-central/raw-file/tip/security/nss/lib/ckfw/builtins/certdata.txt';

Future<void> main(List<String> args) async {
  final String text;
  if (args.isNotEmpty) {
    text = File(args.first).readAsStringSync();
  } else {
    final client = HttpClient();
    final response = await (await client.getUrl(Uri.parse(_source))).close();
    text = await response.transform(utf8.decoder).join();
    client.close();
  }
  final objects = _objects(text);
  final certs = <String, (String, Uint8List)>{};
  final email = <String>{};
  final distrusted = <String>{};
  for (final o in objects) {
    final cls = o['CKA_CLASS'] as String?;
    if (cls == 'CKO_CERTIFICATE' && o['CKA_VALUE'] is Uint8List) {
      final value = o['CKA_VALUE']! as Uint8List;
      certs[_hex(SHA1Digest().process(value))] = (o['CKA_LABEL'] as String? ?? '', value);
    } else if (cls == 'CKO_NSS_TRUST' && o['CKA_CERT_SHA1_HASH'] is Uint8List) {
      final sha1 = _hex(o['CKA_CERT_SHA1_HASH']! as Uint8List);
      if (o['CKA_TRUST_EMAIL_PROTECTION'] == 'CKT_NSS_TRUSTED_DELEGATOR') email.add(sha1);
    }
    // Roots distrusted for mail after a date are left out altogether.
    if (cls == 'CKO_CERTIFICATE' && o['CKA_NSS_EMAIL_DISTRUST_AFTER'] is Uint8List) {
      distrusted.add(_hex(SHA1Digest().process(o['CKA_VALUE']! as Uint8List)));
    }
  }
  final roots = [
    for (final sha1 in email)
      if (certs[sha1] != null && !distrusted.contains(sha1)) certs[sha1]!,
  ]..sort((a, b) => a.$1.compareTo(b.$1));
  final out = StringBuffer()
    ..writeln('// Generated by tool/update_mozilla_roots.dart from NSS certdata.txt; do not edit.')
    ..writeln('// This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.')
    ..writeln()
    ..writeln('/// The root certificates Mozilla trusts for email, as Thunderbird uses them.')
    ..writeln('library;')
    ..writeln()
    ..writeln('/// When the list was taken from NSS.')
    ..writeln("const mozillaEmailRootsDate = '${DateTime.now().toUtc().toIso8601String().substring(0, 10)}';")
    ..writeln()
    ..writeln('/// Name and DER certificate (base64) of each root.')
    ..writeln('const mozillaEmailRoots = <(String, String)>[');
  for (final (label, der) in roots) {
    final b64 = base64.encode(der);
    out.writeln('  (');
    out.writeln('    ${_quote(label)},');
    for (var i = 0; i < b64.length; i += 100) {
      final end = i + 100 > b64.length ? b64.length : i + 100;
      out.writeln("    '${b64.substring(i, end)}'${end == b64.length ? ',' : ''}");
    }
    out.writeln('  ),');
  }
  out.writeln('];');
  File('lib/src/smime/mozilla_roots.dart').writeAsStringSync(out.toString());
  print('${roots.length} roots trusted for email.');
}

String _quote(String s) => "'${s.replaceAll(r'\', r'\\').replaceAll("'", r"\'").replaceAll(r'$', r'\$')}'";

String _hex(List<int> b) => [for (final x in b) x.toRadixString(16).padLeft(2, '0')].join();

/// The objects of certdata.txt: attribute name to a string (CK_* values,
/// UTF8 labels) or bytes (MULTILINE_OCTAL).
List<Map<String, Object>> _objects(String text) {
  final out = <Map<String, Object>>[];
  Map<String, Object>? current;
  final lines = const LineSplitter().convert(text);
  for (var i = 0; i < lines.length; i++) {
    final line = lines[i].trim();
    if (line.isEmpty || line.startsWith('#')) continue;
    final parts = line.split(RegExp(r'\s+'));
    if (parts.length < 2) continue;
    final (name, type) = (parts[0], parts[1]);
    if (name == 'CKA_CLASS') {
      current = {};
      out.add(current);
    }
    if (current == null) continue;
    if (type == 'MULTILINE_OCTAL') {
      final bytes = <int>[];
      for (i++; i < lines.length && lines[i].trim() != 'END'; i++) {
        for (final m in RegExp(r'\\([0-7]{3})').allMatches(lines[i])) {
          bytes.add(int.parse(m.group(1)!, radix: 8));
        }
      }
      current[name] = Uint8List.fromList(bytes);
    } else if (type == 'UTF8') {
      final m = RegExp(r'"(.*)"').firstMatch(line);
      current[name] = m?.group(1) ?? '';
    } else if (parts.length > 2) {
      current[name] = parts[2];
    }
  }
  return out;
}
